DJANGO/Puddle/Puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('items/', include('item.urls')),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

DJANGO/Puddle/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns =[
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signupView, name="signup"),
    path('login/', views.loginView, name="login"),
    path('logout/', views.logoutView, name="logout"),
]

DJANGO/Puddle/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

DJANGO/Puddle/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path('new/', views.new, name="new"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/delete/', views.delete, name="delete"),
]

DJANGO/Puddle/dashboard/models.py
from django.db import models

# Create your models here.

DJANGO/Puddle/item/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name= models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255,blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to="item_images", blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

DJANGO/Puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':'w-full py-4 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your Password',
        'class':'w-full py-4 rounded-xl'
    }))

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':'w-full py-4 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your Email',
        'class':'w-full py-4 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your Password',
        'class':'w-full py-4 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat password',
        'class':'w-full py-4 rounded-xl'
    }))

DJANGO/Puddle/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category':forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name':forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description':forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price':forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image':forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

DJANGO/Puddle/core/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from item.models import Category, Item
from .forms import SignUpForm, LoginForm
from django.contrib.auth import login,logout

# Create your views here.
def index(request):
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)[0:6]
    template = loader.get_template('index.html')
    context = {
        'items':items,
        'categories':categories,
    }
    return HttpResponse(template.render(context, request))

def contact(request):
    template = loader.get_template('contact.html')
    return HttpResponse(template.render())

def signupView(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    template = loader.get_template('signup.html')
    context = {'form':form}
    return HttpResponse(template.render(context, request))

def loginView(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
    else:
        form = LoginForm()

    template = loader.get_template('login.html')
    context = {'form':form}
    return HttpResponse(template.render(context, request))

def logoutView(request):
    logout(request)
    return redirect('/')

DJANGO/Puddle/dashboard/views.py
from django.shortcuts import render, get_object_or_404
from item.models import Item
from django.template import loader
from django.http import HttpResponse

# Create your views here.


def index(request):
    items = Item.objects.filter(created_by=request.user)
    template = loader.get_template('index.html')
    context = {'items':items}
    return HttpResponse(template.render(context, request))

DJANGO/Puddle/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from .models import Item 
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm

# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_item = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    template = loader.get_template('details.html')
    context = {
        'item':item,
        'related_item':related_item,       
    }
    return HttpResponse(template.render(context, request))
    # return render(request, 'details.html', { 'item':item })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST,request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()
    template = loader.get_template('form.html')
    context = {'form':form}
    return HttpResponse(template.render(context, request))


def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    
    return redirect('dashboard:index')

DJANGO/Puddle/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Puddle</a>

        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %}
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Signup</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">login</a>
            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400 ">About</h3>

            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore odit assumenda fuga voluptatem earum, minus reprehenderit optio quam! Dolorem dolores sunt suscipit molestias accusantium dolorum in ratione illum harum debitis.</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400 ">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>
    </footer>
    
</body>
</html>

DJANGO/Puddle/core/templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <h1>Contact page</h1>
{% endblock %}

DJANGO/Puddle/core/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl" alt="">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">{{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
            {% endfor %}
        </div>
    </div>
            
{% endblock %}

DJANGO/Puddle/core/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-x1 p-6">
    <h1 class="mb-6 text-3xl">Login</h1>
    <form action="" method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Username:</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Password:</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-x1">
            {% for x in form %}
                {{ x.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

DJANGO/Puddle/core/templates/signup.html
{%  extends 'base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-x1 p-6">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form action="" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="" class="inline-block mb-2">Username:</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label for="" class="inline-block mb-2">Email:</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label for="" class="inline-block mb-2">Password:</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label for="" class="inline-block mb-2">Repeat password:</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-x1">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

DJANGO/Puddle/dashboard/templates/index.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl" alt="">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">{{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
            {% endfor %}
        </div>
    </div>
            
{% endblock %}

DJANGO/Puddle/item/templates/details.html
{% extends 'base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url }}" class="rounded-xl" alt="">
        </div>

        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
            <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by }}</p>

            {%if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description: </strong></br>
                {{ item.description }}
            </p>
            {% endif %}

            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>This is your item!</p>

                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                </div>
            {% else %}
                <a href="" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
            {% endif %}

            
        </div>

        <h2 class="mb-12 text-2xl text-center">Related items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in related_item %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl" alt="">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">{{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

DJANGO/Puddle/item/templates/form.html
{% extends 'base.html' %}

{% block title %}New item{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">New Item</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for x in form %}
                    {{ x.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 mt-6 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
{% endblock %}